name: Build Android Bundle (AAB)

on:
  push:
    branches: [ main ] # Agar asosiy branchingiz nomi master bo'lsa, master deb o'zgartiring

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Cordova
      run: npm install -g cordova

    - name: Add Android Platform
      run: cordova platform add android

    - name: Build Android Release Bundle (AAB)
      run: cordova build android --release -- --packageType=bundle

    - name: Upload AAB Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release-bundle
        path: platforms/android/app/build/outputs/bundle/release/app-release.aab
