name: Build Android Bundle (AAB)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Initialize Project and Platform
        run: |
          npm install
          cordova platform add android

      - name: Build Android Release Bundle
        run: cordova build android --release -- --packageType=bundle

      - name: Sign Android Release
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: platforms/android/app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload Signed AAB
        uses: actions/upload-artifact@v4
        with:
          name: flipp-bird-final-aab
          path: ${{ steps.sign_app.outputs.signedReleaseFile }}
